<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://nurolopher" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://nurolopher" xmlns:intf="http://nurolopher" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema targetNamespace="http://nurolopher" xmlns="http://www.w3.org/2001/XMLSchema">
   <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
   <complexType name="ArrayOfArrayOf_xsd_int">
    <complexContent>
     <restriction base="soapenc:Array">
      <attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:int[][]"/>
     </restriction>
    </complexContent>
   </complexType>
  </schema>
 </wsdl:types>

   <wsdl:message name="multiplyResponse">

      <wsdl:part name="multiplyReturn" type="impl:ArrayOfArrayOf_xsd_int"/>

   </wsdl:message>

   <wsdl:message name="multiplyRequest">

      <wsdl:part name="A" type="impl:ArrayOfArrayOf_xsd_int"/>

      <wsdl:part name="B" type="impl:ArrayOfArrayOf_xsd_int"/>

   </wsdl:message>

   <wsdl:portType name="Matrix">

      <wsdl:operation name="multiply" parameterOrder="A B">

         <wsdl:input message="impl:multiplyRequest" name="multiplyRequest"/>

         <wsdl:output message="impl:multiplyResponse" name="multiplyResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="MatrixSoapBinding" type="impl:Matrix">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="multiply">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="multiplyRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://nurolopher" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="multiplyResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://nurolopher" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="MatrixService">

      <wsdl:port binding="impl:MatrixSoapBinding" name="Matrix">

         <wsdlsoap:address location="http://localhost:8080/services/nurolopher/Matrix"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
